# Check code style and run tests
name: Run tests for project

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout latest code
      - uses: actions/checkout@v2
      # Install Java 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      # Run code linter and unit tests
      - name: Check style and run unit tests
        run: ./gradlew check --rerun-tasks
