# Check code style and run tests
name: Lint code and run tests for project

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Lint code and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run code linter and run unit tests
        run: ./gradlew check --rerun-tasks
